{ config, ... }:
{
  nixos.gui =
    { pkgs, ... }:
    {
      services.greetd = {
        enable = true;
        settings = {
          # Autologin straight into Hyprland via UWSM at boot. Command copied
          # verbatim from the working Exec= line in the hyprland-uwsm.desktop
          # session entry generated by programs.hyprland.withUWSM.
          initial_session = {
            command = "${pkgs.uwsm}/bin/uwsm start -e -D Hyprland hyprland.desktop";
            inherit (config.my) user;
          };
          # initial_session only fires once at boot; falls back to this normal
          # login prompt if the session ever ends (e.g. logout).
          default_session.command = "${pkgs.greetd}/bin/agreety --cmd '${pkgs.uwsm}/bin/uwsm start -e -D Hyprland hyprland.desktop'";
        };
      };
      security.pam.services.greetd.enableGnomeKeyring = true;
    };
}
